import type { PantryItem, Recipe } from "./types";

const img = (q: string) =>
  `https://images.unsplash.com/${q}?auto=format&fit=crop&w=900&q=70`;

export function seedRecipes(): Recipe[] {
  const now = Date.now();
  const base = (i: number, r: Omit<Recipe, "id" | "createdAt" | "updatedAt">): Recipe => ({
    ...r,
    id: `seed-${i}`,
    createdAt: now - i * 1000,
    updatedAt: now - i * 1000,
  });

  return [
    base(1, {
      title: "Sopa de Tomate Rostizado con Albahaca",
      title_en: "Roasted Tomato & Basil Soup",
      description:
        "Una receta reconfortante que aprovecha al máximo los tomates maduros y un toque de albahaca fresca.",
      description_en:
        "A comforting recipe that makes the most of ripe tomatoes with a touch of fresh basil.",
      image: img("photo-1547592180-85f173990554/1600x900"),
      category: "soup",
      difficulty: "easy",
      timeMinutes: 25,
      servings: 4,
      ingredients: [
        { name: "Tomates maduros", quantity: "1 kg" },
        { name: "Cebolla", quantity: "1" },
        { name: "Ajo", quantity: "3 dientes" },
        { name: "Albahaca fresca", quantity: "1 puñado" },
        { name: "Aceite de oliva", quantity: "3 cdas" },
        { name: "Sal", quantity: "al gusto" },
      ],
      ingredients_en: [
        { name: "Ripe tomatoes", quantity: "1 kg" },
        { name: "Onion", quantity: "1" },
        { name: "Garlic", quantity: "3 cloves" },
        { name: "Fresh basil", quantity: "1 handful" },
        { name: "Olive oil", quantity: "3 tbsp" },
        { name: "Salt", quantity: "to taste" },
      ],
      equipment: ["Horno", "Licuadora", "Olla"],
      equipment_en: ["Oven", "Blender", "Pot"],
      steps: [
        "Precalienta el horno a 200°C. Corta los tomates a la mitad y colócalos en una bandeja con la cebolla y el ajo.",
        "Rocía con aceite de oliva y sal. Asa durante 25 minutos hasta que los bordes se doren.",
        "Pasa todo a la licuadora con la albahaca y procesa hasta obtener una crema suave.",
        "Calienta en una olla 5 minutos. Sirve con un chorrito de aceite y hojas de albahaca.",
      ],
      steps_en: [
        "Preheat oven to 200°C/400°F. Halve tomatoes and place on a tray with onion and garlic.",
        "Drizzle with olive oil and salt. Roast 25 minutes until edges caramelise.",
        "Blend everything with basil until smooth.",
        "Warm in a pot for 5 minutes. Serve with olive oil and basil leaves.",
      ],
      featured: true,
    }),
    base(2, {
      title: "Ensalada Caprese Rústica",
      title_en: "Rustic Caprese Salad",
      description:
        "Fresca, rápida y sin necesidad de cocinar. Ideal para aprovechar tus tomates más jugosos.",
      description_en: "Fresh, fast, and no cooking needed. Perfect for the juiciest tomatoes.",
      image: img("photo-1592417817038-d13fd7342605/1600x900"),
      category: "salad",
      difficulty: "easy",
      timeMinutes: 10,
      servings: 2,
      ingredients: [
        { name: "Tomate", quantity: "2 grandes" },
        { name: "Mozzarella fresca", quantity: "200g" },
        { name: "Albahaca fresca", quantity: "10 hojas" },
        { name: "Aceite de oliva", quantity: "2 cdas" },
        { name: "Sal y pimienta", quantity: "al gusto" },
      ],
      ingredients_en: [
        { name: "Tomato", quantity: "2 large" },
        { name: "Fresh mozzarella", quantity: "200g" },
        { name: "Fresh basil", quantity: "10 leaves" },
        { name: "Olive oil", quantity: "2 tbsp" },
        { name: "Salt & pepper", quantity: "to taste" },
      ],
      equipment: ["Cuchillo", "Tabla"],
      equipment_en: ["Knife", "Board"],
      steps: [
        "Corta los tomates y la mozzarella en rodajas del mismo grosor.",
        "Alterna en un plato con las hojas de albahaca.",
        "Riega con aceite de oliva, sal y pimienta. Sirve de inmediato.",
      ],
      steps_en: [
        "Slice tomatoes and mozzarella to similar thickness.",
        "Alternate on a plate with basil leaves.",
        "Drizzle with olive oil, salt and pepper. Serve immediately.",
      ],
    }),
    base(3, {
      title: "Salsa Base de Tomate y Cebolla",
      title_en: "Tomato & Onion Base Sauce",
      description:
        "El bloque de construcción perfecto para pastas, guisos y pizzas, usando tus tomates frescos.",
      description_en: "The perfect base for pastas, stews and pizzas, using fresh tomatoes.",
      image: img("photo-1608897013039-887f21d8c804/1600x900"),
      category: "sauce",
      difficulty: "medium",
      timeMinutes: 45,
      servings: 6,
      ingredients: [
        { name: "Tomates pelados", quantity: "800g" },
        { name: "Cebolla picada", quantity: "1" },
        { name: "Ajo", quantity: "2 dientes" },
        { name: "Aceite de oliva", quantity: "2 cdas" },
        { name: "Orégano seco", quantity: "1 cdita" },
      ],
      equipment: ["Olla", "Cuchara"],
      steps: [
        "Sofríe la cebolla en aceite hasta dorar. Añade el ajo 1 minuto.",
        "Agrega los tomates pelados aplastados y el orégano.",
        "Cuece a fuego bajo 30 minutos removiendo. Ajusta sal y reserva.",
      ],
    }),
    base(4, {
      title: "Pan de Masa Madre Rústico",
      title_en: "Rustic Sourdough Bread",
      description:
        "Una receta clásica de panadería artesanal. Exterior crujiente, miga suave y aireada con ese toque ácido de la masa madre.",
      description_en:
        "Classic artisan sourdough. Crisp crust, airy crumb and that signature tang.",
      image: img("photo-1509440159596-0249088772ff/1600x900"),
      category: "bakery",
      difficulty: "hard",
      timeMinutes: 45,
      servings: 8,
      ingredients: [
        { name: "Harina de fuerza", quantity: "500g" },
        { name: "Agua tibia", quantity: "350ml" },
        { name: "Masa madre activa", quantity: "100g" },
        { name: "Sal marina fina", quantity: "10g" },
      ],
      equipment: ["Horno 250°C", "Olla de hierro", "Bol grande", "Cuchilla (lame)"],
      equipment_en: ["Oven 250°C", "Dutch oven", "Large bowl", "Lame"],
      steps: [
        "Autólisis: mezcla harina y agua, deja reposar 1 hora.",
        "Incorpora la masa madre y la sal. Amasa con técnica slap & fold 5–7 minutos.",
        "Fermentación en bloque 3 horas con pliegues cada 30 minutos.",
        "Forma una hogaza, enharina y deja en banneton en frío 12–16 horas.",
        "Hornea en olla cerrada 20 min a 250°C, luego destapa 20 min más.",
      ],
      featured: true,
    }),
    base(5, {
      title: "Pizza Margarita Clásica",
      title_en: "Classic Margherita Pizza",
      description: "Masa fina, salsa de tomate, mozzarella fundente y albahaca fresca.",
      description_en: "Thin crust, tomato sauce, melting mozzarella and fresh basil.",
      image: img("photo-1604068549290-dea0e4a305ca/1600x900"),
      category: "dinner",
      difficulty: "medium",
      timeMinutes: 45,
      servings: 2,
      ingredients: [
        { name: "Masa de pizza", quantity: "1" },
        { name: "Salsa de tomate", quantity: "150g" },
        { name: "Mozzarella", quantity: "200g" },
        { name: "Albahaca fresca", quantity: "al gusto" },
      ],
      equipment: ["Horno", "Bandeja"],
      steps: [
        "Precalienta el horno al máximo con la bandeja dentro.",
        "Estira la masa, añade salsa y mozzarella.",
        "Hornea 8–10 minutos hasta que burbujee. Añade albahaca al sacar.",
      ],
    }),
    base(6, {
      title: "Avena de la Abuela",
      title_en: "Grandma's Oatmeal",
      description: "Avena cremosa con frutos rojos y un toque de miel.",
      description_en: "Creamy oatmeal with berries and a touch of honey.",
      image: img("photo-1517673132405-a56a62b18caf/1600x900"),
      category: "breakfast",
      difficulty: "easy",
      timeMinutes: 15,
      servings: 2,
      ingredients: [
        { name: "Avena", quantity: "1 taza" },
        { name: "Leche", quantity: "2 tazas" },
        { name: "Frutos rojos", quantity: "1 taza" },
        { name: "Miel", quantity: "2 cdas" },
      ],
      equipment: ["Olla pequeña"],
      steps: [
        "Lleva la leche a fuego medio.",
        "Añade la avena y cuece 5 minutos removiendo.",
        "Sirve con frutos rojos y miel.",
      ],
    }),
    base(7, {
      title: "Pasta Casera al Pesto",
      title_en: "Homemade Pesto Pasta",
      description: "Spaghetti con pesto fresco de albahaca y piñones.",
      description_en: "Spaghetti tossed in fresh basil and pine nut pesto.",
      image: img("photo-1551183053-bf91a1d81141/1600x900"),
      category: "lunch",
      difficulty: "easy",
      timeMinutes: 35,
      servings: 4,
      ingredients: [
        { name: "Spaghetti", quantity: "400g" },
        { name: "Albahaca fresca", quantity: "60g" },
        { name: "Piñones", quantity: "30g" },
        { name: "Parmesano", quantity: "50g" },
        { name: "Aceite de oliva", quantity: "100ml" },
        { name: "Ajo", quantity: "1 diente" },
      ],
      equipment: ["Olla", "Procesador"],
      steps: [
        "Cuece la pasta en agua con sal según el paquete.",
        "Procesa albahaca, ajo, piñones, parmesano y aceite.",
        "Mezcla con la pasta caliente y un poco de agua de cocción.",
      ],
    }),
    base(8, {
      title: "Delicia de Capas",
      title_en: "Layered Delight",
      description: "Postre frío en vaso con galleta, crema y frutos rojos.",
      description_en: "Cold dessert in a glass with biscuit, cream and berries.",
      image: img("photo-1587314168485-3236d6710814/1600x900"),
      category: "dessert",
      difficulty: "easy",
      timeMinutes: 60,
      servings: 4,
      ingredients: [
        { name: "Galletas", quantity: "200g" },
        { name: "Queso crema", quantity: "300g" },
        { name: "Crema de leche", quantity: "200ml" },
        { name: "Frutos rojos", quantity: "150g" },
        { name: "Azúcar", quantity: "80g" },
      ],
      equipment: ["Vasos", "Batidora"],
      steps: [
        "Tritura las galletas. Bate queso crema, crema y azúcar.",
        "Alterna capas en vasos: galleta, crema, frutos rojos.",
        "Refrigera al menos 1 hora antes de servir.",
      ],
    }),
    base(9, {
      title: "Ensalada Rústica de la Huerta",
      title_en: "Garden Rustic Salad",
      description: "Mezcla fresca y reconfortante de vegetales asados con vinagreta de hierbas.",
      description_en: "Fresh, hearty mix of roasted vegetables with herb vinaigrette.",
      image: img("photo-1540420773420-3366772f4999/1600x900"),
      category: "salad",
      difficulty: "easy",
      timeMinutes: 25,
      servings: 2,
      ingredients: [
        { name: "Mezcla de hojas verdes", quantity: "150g" },
        { name: "Tomates cherry", quantity: "200g" },
        { name: "Pepino", quantity: "1" },
        { name: "Aceite de oliva", quantity: "3 cdas" },
        { name: "Vinagre balsámico", quantity: "1 cda" },
      ],
      equipment: ["Bol", "Cuchillo"],
      steps: [
        "Lava y corta los vegetales.",
        "Mezcla aceite y vinagre con sal.",
        "Combina todo y sirve.",
      ],
      featured: true,
    }),
    base(10, {
      title: "Tortilla Española",
      title_en: "Spanish Omelette",
      description: "Clásica tortilla de patatas con cebolla pochada.",
      description_en: "Classic potato omelette with slow-cooked onion.",
      image: img("photo-1568901346375-23c9450c58cd/1600x900"),
      category: "lunch",
      difficulty: "medium",
      timeMinutes: 40,
      servings: 4,
      ingredients: [
        { name: "Patatas", quantity: "500g" },
        { name: "Cebolla", quantity: "1" },
        { name: "Huevos", quantity: "6" },
        { name: "Aceite de oliva", quantity: "200ml" },
        { name: "Sal", quantity: "al gusto" },
      ],
      equipment: ["Sartén", "Plato grande"],
      steps: [
        "Confita patatas y cebolla en aceite a fuego bajo 25 minutos.",
        "Bate los huevos, mezcla con las patatas escurridas.",
        "Cuaja en sartén 4 minutos por lado dándole la vuelta con un plato.",
      ],
    }),
    base(11, {
      title: "Smoothie Verde",
      title_en: "Green Smoothie",
      description: "Bebida refrescante con espinacas, plátano y manzana.",
      description_en: "Refreshing drink with spinach, banana and apple.",
      image: img("photo-1610970881699-44a5587cabec/1600x900"),
      category: "drink",
      difficulty: "easy",
      timeMinutes: 5,
      servings: 1,
      ingredients: [
        { name: "Espinacas frescas", quantity: "1 taza" },
        { name: "Plátano", quantity: "1" },
        { name: "Manzana", quantity: "1" },
        { name: "Agua", quantity: "200ml" },
      ],
      equipment: ["Licuadora"],
      steps: ["Pela y trocea las frutas.", "Licúa todo con el agua hasta que esté cremoso."],
    }),
    base(12, {
      title: "Curry de Garbanzos",
      title_en: "Chickpea Curry",
      description: "Reconfortante curry vegetariano con leche de coco.",
      description_en: "Comforting vegetarian curry with coconut milk.",
      image: img("photo-1565557623262-b51c2513a641/1600x900"),
      category: "dinner",
      difficulty: "medium",
      timeMinutes: 35,
      servings: 4,
      ingredients: [
        { name: "Garbanzos cocidos", quantity: "400g" },
        { name: "Leche de coco", quantity: "400ml" },
        { name: "Cebolla", quantity: "1" },
        { name: "Ajo", quantity: "3 dientes" },
        { name: "Curry en polvo", quantity: "2 cdas" },
        { name: "Tomate triturado", quantity: "200g" },
      ],
      equipment: ["Olla"],
      steps: [
        "Sofríe cebolla y ajo. Añade el curry y tuesta 1 minuto.",
        "Agrega tomate y leche de coco. Cuece 10 minutos.",
        "Incorpora garbanzos y cuece 10 minutos más. Sirve con arroz.",
      ],
    }),
    base(13, {
      title: "Guacamole Clásico",
      title_en: "Classic Guacamole",
      description: "Aguacate fresco con lima, cilantro y un toque picante.",
      description_en: "Fresh avocado with lime, cilantro and a touch of heat.",
      image: img("photo-1600335895229-6e75511892c8/1600x900"),
      category: "snack",
      difficulty: "easy",
      timeMinutes: 10,
      servings: 4,
      ingredients: [
        { name: "Aguacate maduro", quantity: "3" },
        { name: "Lima", quantity: "1" },
        { name: "Cilantro", quantity: "1 puñado" },
        { name: "Cebolla roja", quantity: "1/2" },
        { name: "Chile", quantity: "1" },
      ],
      equipment: ["Bol", "Tenedor"],
      steps: ["Aplasta los aguacates.", "Mezcla con cebolla, cilantro, chile y zumo de lima."],
    }),
    base(14, {
      title: "Galletas de Avena y Chocolate",
      title_en: "Oat & Chocolate Cookies",
      description: "Crujientes por fuera y tiernas por dentro, con chips de chocolate.",
      description_en: "Crisp outside, tender inside, packed with chocolate chips.",
      image: img("photo-1499636136210-6f4ee915583e/1600x900"),
      category: "dessert",
      difficulty: "easy",
      timeMinutes: 25,
      servings: 12,
      ingredients: [
        { name: "Avena", quantity: "150g" },
        { name: "Harina", quantity: "100g" },
        { name: "Mantequilla", quantity: "100g" },
        { name: "Azúcar moreno", quantity: "100g" },
        { name: "Huevo", quantity: "1" },
        { name: "Chips de chocolate", quantity: "100g" },
      ],
      equipment: ["Horno 180°C", "Bandeja"],
      steps: [
        "Bate mantequilla y azúcar. Añade huevo y mezcla.",
        "Incorpora harina, avena y chocolate.",
        "Forma bolas, aplasta y hornea 12 minutos a 180°C.",
      ],
    }),
    base(15, {
      title: "Limonada de Hierbabuena",
      title_en: "Mint Lemonade",
      description: "Refresco casero perfecto para días calurosos.",
      description_en: "Homemade cooler perfect for warm days.",
      image: img("photo-1556881286-fc6915169721/1600x900"),
      category: "drink",
      difficulty: "easy",
      timeMinutes: 10,
      servings: 4,
      ingredients: [
        { name: "Limones", quantity: "4" },
        { name: "Agua fría", quantity: "1L" },
        { name: "Azúcar", quantity: "100g" },
        { name: "Hierbabuena", quantity: "1 ramita" },
      ],
      equipment: ["Jarra"],
      steps: ["Exprime los limones.", "Mezcla con agua, azúcar y hierbabuena. Sirve con hielo."],
    }),
  ];
}

import type { PantryCategory, Unit } from "./types";

export function seedPantryCategories(): PantryCategory[] {
  return [
    { id: "c1", name: "Lácteos & Huevos", name_en: "Dairy & Eggs", emoji: "🥚", order: 1 },
    { id: "c2", name: "Verduras Frescas", name_en: "Fresh Vegetables", emoji: "🥦", order: 2 },
    { id: "c3", name: "Frutas", name_en: "Fruits", emoji: "🍎", order: 3 },
    { id: "c4", name: "Carnes", name_en: "Meat", emoji: "🥩", order: 4 },
    { id: "c5", name: "Pescado", name_en: "Fish", emoji: "🐟", order: 5 },
    { id: "c6", name: "Especias Secas", name_en: "Dry Spices", emoji: "🌶️", order: 6 },
    { id: "c7", name: "Aceites & Vinagres", name_en: "Oils & Vinegars", emoji: "🫒", order: 7 },
    { id: "c8", name: "Granos & Pastas", name_en: "Grains & Pasta", emoji: "🌾", order: 8 },
    { id: "c9", name: "Otros", name_en: "Other", emoji: "🧂", order: 99 },
  ];
}

export function seedPantry(): PantryItem[] {
  const item = (
    id: string, name: string, name_en: string, category: string,
    quantity: number, unit: Unit, available = true,
  ): PantryItem => ({ id, name, name_en, category, quantity, unit, available });

  return [
    item("p1", "Leche Entera", "Whole milk", "Lácteos & Huevos", 1, "L"),
    item("p2", "Huevos", "Eggs", "Lácteos & Huevos", 12, "ud"),
    item("p3", "Mantequilla sin sal", "Unsalted butter", "Lácteos & Huevos", 0, "g", false),
    item("p4", "Cebolla Blanca", "White onion", "Verduras Frescas", 3, "ud"),
    item("p5", "Zanahorias", "Carrots", "Verduras Frescas", 0, "ud", false),
    item("p6", "Ajo", "Garlic", "Verduras Frescas", 2, "ud"),
    item("p7", "Tomate", "Tomato", "Verduras Frescas", 5, "ud"),
    item("p8", "Albahaca fresca", "Fresh basil", "Verduras Frescas", 1, "ud"),
    item("p9", "Pimienta Negra", "Black pepper", "Especias Secas", 50, "g"),
    item("p10", "Sal Marina", "Sea salt", "Especias Secas", 200, "g"),
    item("p11", "Orégano Seco", "Dried oregano", "Especias Secas", 30, "g"),
    item("p12", "Aceite de Oliva", "Olive oil", "Aceites & Vinagres", 750, "ml"),
    item("p13", "Harina", "Flour", "Granos & Pastas", 1, "kg"),
    item("p14", "Avena", "Oats", "Granos & Pastas", 500, "g"),
    item("p15", "Spaghetti", "Spaghetti", "Granos & Pastas", 500, "g"),
    item("p16", "Manzana", "Apple", "Frutas", 4, "ud"),
    item("p17", "Plátano", "Banana", "Frutas", 3, "ud"),
  ];
}
